---
stages:
  - build-and-push
build:
  stage: build-and-push
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_ECR_URI: $AWS_ECR_URI
    HTTP_PROXY: $HTTP_PROXY
    HTTPS_PROXY: $HTTPS_PROXY
    NO_PROXY: $NO_PROXY
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint:
      - /busybox/sh
      - -c
  before_script:
    - |
      cat > /kaniko/.docker/config.json << EOF
      {"credsStore": "ecr-login"}
      EOF
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --build-arg http_proxy="${HTTP_PROXY}"
      --build-arg https_proxy="${HTTPS_PROXY}"
      --build-arg no_proxy="${NO_PROXY}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${AWS_ECR_URI}:${CI_COMMIT_TAG}"
  rules:
    - if: $CI_COMMIT_TAG
